import type { Metadata } from "next";
import "./globals.css";
import { Cairo } from "next/font/google";


const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "700", "500", "600"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
